version: 2

sources:
    - name: staging 
      database: pivotal-purpose-347613
      schema: data_extract
      tables:
        - name: accident_16
        - name: casualty_16
        - name: vehicle_16

